version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: HomeClimate
    restart: unless-stopped
    env_file: .env
    environment:
      - MQTT_HOST=$MQTT_HOST
      - MQTT_PORT=$MQTT_PORT
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: /home/node/app/node_modules/.bin/nodemon app.js

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
  